language: haskell
cabal: "3.0"
ghc:
  - "8.8.3"

cache:
  directories:
  - "$HOME/.cabal/store"

branches:
  only:
    - master

install:
  - travis_wait 60 cabal install --only-dependencies

script:
  - cabal configure
  - cabal build
  - cabal exec site build
  - cabal exec site check
