language: haskell
cabal: "3.0"
ghc:
  - "8.8.3"

branches:
  only:
    - master

install:
  - cabal install --only-dependencies

script:
  - cabal configure
  - cabal build
  - cabal exec site build
  - cabal exec site check
