name: Site

on:
  push:
    branches: [master]

jobs:
  build: 
    name: Build and check

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.4'

      - name: Dependenies
        run: cabal freeze

      - name: Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          key: ${{ runner.os }}-8.10.5-${{ hashFiles('cabal.project.freeze') }}

      - name: Compile and check
        run: cabal configure
      - run: cabal build
      - run: cabal exec site build
      - run: cabal exec site check
