name: Site

on:
  push:
    branches: [master]

jobs:
  build: 
    name: Build and check

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.4'

      - name: Dependenies
        run: cabal configure
    
      - run: cabal build
      - run: cabal exec site build
      - run: cabal exec site check
